#Include "Protheus.ch"
#Include "totvs.ch"

User Function funTraduz(_cString,_cIdioma)

	Local aPalavPort :=  {"Contagem total","Bolores e Leveduras","Estafilococos aureus","Coliformes Totais","Col. Termotolerantes","Salmonella spp","Bacillus cereus",;
				"Ph","APROVADO SEM RESTRICOES***","Nota","Minimo","Maximo","Produto","Data da Producao","Cliente","Validade","Pedido","Container","Lote","Qtd.Expedida","Certificado de Analises","Operacao",;
				"Certificado de Qualidade","presenca","ausencia","grupo","empresa","folha","dt.ref","emissão","janeiro","fevereiro","março","abril","maio","junho",;
				"julho","agosto","setembro","outubro","novembro","desembro","Ensaio","alimenticios","Metodo","Un. Medido","Especificado","Encontrados","Contagem Total",;
				"Contagem de Bolores e Leveduras","Contagem de Coliformes Totais","Contagem de Staphylococcus Aureus","ShelfLife 180 Dias","LABFIS","Viscosidade",;
				"Aprovado Sem Restricoes","Contaminantes","Analise Externa","AFLATOXINA","ARSÊNICO","CHUMBO","CÂDMIO","REALIZAO APENAS LATAS LCO","ESTANHO","Laudo",;
				"Data. Laudo","Qtde. Rej","Just. Laudo","Aprovado sem Restricoes","Metodos","RESULTADOS","Unidade","Máx","ITENS","Analista de Laboratorio",;
				"Analista Microbiologia","Coordenadorade CQ e GQ","DENSIDADE","GORDURA","SOLIDOS TOTAIS","ACIDEZ","pH","VISCOSIDADE","BRIX","UMIDADE","CRISTALIZACAO",;
				"VISCOSIDADE","dia","SENSORIAL","LABFIS","ASPECTO","NOTA","COR","ODOR","TEXTURA","PH 4 DIAS","EXP(WAL,TO,CH,VAN,OM","MERCADO EXTERNO","SHELF LIFE 210 DIAS",;
				"SHELF LIFE 240 DIAS","CONTRA PROVA 150 DIA","SHELF LIFE 60 DIAS","LIBERACAO PROCESSO","SHELF LIFE 150 DIAS","PREPARO CRE HERCULES","INST BAG CARGIL",;
				"MICROBIOLGIA","FISICO QUIMICA","SHELF LIFE 360 DIAS","SHELF LIFE 510 DIAS","SHELF LIFE 540 DIAS"," ACOMP. ENVASE","FISICO QUIMICAS","ENVASE LCO",;
				"TANQUE ESTOCAGEM","ESTABILIZADO","SHELF LIFE 120 DIAS","PREPARO CRE ING/ESP","LIOTÉCNICA/GRANEL","SHELF LIFE 180 DIAS","SHELF LIFE 390 DIAS","CONTRA PROVA",;
				"PASTEURIZADO","SHELF LIFE 30 DIAS","SHELF LIFE 90 DIAS","NACIONAL","ARCOR-GRANEL","ARCOR BIG BAG 5KG","MISTURA DE CHOCOLATE","ACOMP. ENVASE",;
				"LEITE PADRONIZADO","SHELF LIFE 270 DIAS","SHELF LIFE 450 DIAS","SHELF LIFE 480 DIAS","MICROBILOGIA","LIBERACAO ESTOCAGEM","LEITE UHT ACOMP",;
				"PREPARO CREME MOCOCA","SHELF LIFE 420 DIAS","MICROLOGIA","MICROBIOLOGIA","LEITE UHT PA FQ","XAROPE BBL","ENCAIXOTAMENTO BAG","FISICO QUIMICA 1ºDIA",;
				"CREME UHT PA FQ","ACOMPANHAMENTO SILO","PH DE 4 DIAS","SENSORIAL","EXP(LA CAMP,CAMPESTR","ACOMPANHAMENTO","PADRONIZADO","INSTITUCIONAL(BAG)",;
				"EXPORTACAO (EUA)","FASES","CREME UHT ACOMP","SHELF LIFE 300 DIAS","SHELF LIFE 330 DIAS","ENCAIXOTAMENTO LCO","ACOMP. CREME CRU","G/M²","PORCENTAGEM",;
				"NÍVEL","MILIGRAMA/QUILOGRAMA","JOGO","QUILOGRAMA","KIT","POLEGADAS","JARDA","CENTIPOISE","NANOMETRO","UNIDADE FORMADORA DE COLONIAS POR GRAMAS",;
				"FOLHA","ROTACAO POR MINUTO","GRAUS BRIX","NUMERO POR 100g","ACIDEZ DORNIC","GRAMAS","GRAMAS POR CENTIMETRO QUADRADO","GRAMAS POR METRO CUBICO",;
				"MICRO GRAMA/QUILOGRAMA","ROLO","BALDE","CENTIMETRO","TONELADA LIQUIDA","MINUTOS","UNID FORMADORA DE COLÔNIA","MILHEIRO","GRAUS Z","POTENCIAL DE HIDROGENIO",;
				"UNIDADE FORMADORA DE COLONIAS","MESH","CONJUNTO","°DORNIC","NIVEL","GRAMAS POR METRO QUDRADO","DECIMETRO","DUZIA","FOLHAS","GROZA","HORA","LITRO","LATA",;
				"ºGL","PARTICULAS MAGNETICAS","UFC/100cm²","ML","MICRO","BLOCO","NITIDEZ POR TURBIDEZ","UNIDADE","ºZ","UI-Máx","POTENCIAL DE HIDROGÊNIO","GRAUS GL",;
				"ºD","BAR","kg/m²","FRASCO","PACOTE","METRO QUADRADO","PAR","ACIDO LATICO","QUILOGRAMA FORCA POR CENTIMETRO QUADRADO","GRAUS CENTIGRADOS","UNIDADE FORMADORA DE COLONIAS POR ML",;
				"CONTAGEM DE CELULAS SOMATICAS","~HAZEN","NEWTON POR METRO","MILIGRAMA","GRAMAS POR LITRO","CENTIMETRO QUADRADO","MILAMPER","ARROBA","CENTIMETRO CUBICO",;
				"CENTO","CAIXA","GRAMA","LIBRA","METRO CUBICO","METRO","ONCA","SEGUNDOS","Volume","GRAMAS POR ML","PES","GALAO","MILILITRO","PECA","CINZAS","Kgf/cm","MIRIAMETRO",;
				"MINUTO","TESTE","GRAMAS POR METRO","QUILOGRAMA FORCA POR CENTIMETRO","SACO","NOTA DE1 A 5","ESCALA DE UMIDADE","GRAUS H","BANDEJA","MILIMETRO","CENTIGRADOS",;
				"GRAMAS POR MILILITROS","QUILOGRAMA FORCA POR CENTIMETRO CUBICO","PARTE POR MILHAO","UNID.FOR.COLONIAS POR CENTIMETRO QUADRAD","NUMERO MAIS PROVAVEL",;
				"ATIVIDADE PROTEASE","mPas","Cps","TONELADA","GRAMAS POR CENTIMETRO","GRAMAS POR CENTIMETRO CUBICO","CONTAGEM TOTAL","CONTAGEM DE COLIFORMES TOTAIS","BACILLUS CEREUS","VISCOSIDADE 1ºDIA","BRIX 1ºDIA","SENSORIAL","VISCOSIDADE 6°DIA","GORDURA","TEMPERATURA","VISCOSIDADE",;                            
				"ASPECTO","COR","VOLUME (TANQUE)","CONTAGEM DE STAPHYLOCOCCUS AUREUS","ACIDEZ","CONTAGEM DE BOLORES E LEVEDURAS","SORO","PEROXIDASE","BRIX","CONTAGEM DE BACILLUS SPOROTHERMODURANS",; 
				"PSICOTROFICOS","DENSIDADE","CONTAGEM DE COLIFORMES TERMOTOLERANTES","FOSFATASE","CONTAGEM DE MESÓFILOS AERÓBIOS VIÁVEIS","ODOR","EXTRATO SECO TOTAL","CRIOSCOPIA","SALMONELA",;                              
				"FORMALDEIDO (METODO LENTO)","FORMALDEIDO (METODO RAPIDO)","TEXTURA","SABOR","pH","ALCOOL","UMIDADE","CRISTALIZACAO","pH 1ºDIA","SOLIDOS TOTAIS","EXTRATO SECO DESENGORDURADO",;            
				"CONTAGEM DE COLIFORMES TERMOTOLERANTE","SOLIDOS NÃO GORDUROSOS","PEROXIDO DE HIDROGÊNIO","CONTAGEM DE MICROORGANISMOS PSICOTROFICO","ENCAIXOTAMENTO BBL","ENVASE CRE","ENVASE TP ","FABRICAÇÃO LEITE PO ","DESN/PASTEURIZ","ENVASE LCO","FABRICAÇÃO MIX BBL","FABRICAÇÃO BBL","FABRICAÇÃO CRE","ENVASE 1 KG ","RECEBIMENTO SORO LIQ","RECEBIMENTO DESN",;
				"ENVASE BAG","ENVASE BBL","FABRICAÇÃO LCO","FABRICAÇÃO MIXLCO ","FABRICAÇÃO MIX CRE","RESFRIAMENTO LEITE","FABRICAÇÃO SORO PO","ENCAIXOT LEITE","ENVASE CREME","FABRICAÇÃO CALDA","ENVASE LEITE UHT","ENCAIXOTAMENTO 1KG",;
				"ENCAIXOTAMENTO BAG","ENCAIXOTAMENTO TP ","ENCAIXOTAMENTO CRE","FABRICAÇÃO XAROPE ","RECEBIMENTO CREME ","PREPARACAO CREME","RECEBIMENTO PERM","ENCAIX LEITE","PADRONIZAÇÃO LCO","RECEBIMENTO LEITE ","RESFRIAMENTO CREME",;
				"ENCAIXOTAMENTO LCO","PADRONIZACAO LOTE ","ENCAIXOT CREME","ENVASE 1KG","FABRICACAO LCO","Aflatoxina","Arsênico","Chumbo","Câdmio","Estanho","Analise Externa","ACEITO COM DESVIO SIMPLES","REJEITADO TOTALMENTE","ACEITO COM DESVIO GRAVE","COM SELECAO PELO PRODUTO","LIBERACAO URGENTE"}

Local aPalavEsp :=   {"Contaje Total","Mohos y Levaduras","Estafilococos aureus","Coliformes Totales","Salmonella spp","Col. Termotolerantes","Bacillus cereus",;
				"Ph","APROBADO SIN RESTRICIONES ***","Nota","Mínimo","Máximo","Producto","Fecha de producción","Cliente","Duracion","Orden","Envase","Mucho","Cantidad emitida","Certificado de análisis",;
				"Operación","Certificado de calidad","presencia","ausencia","grupo","empresa","hoja","dt.ref","emisión","enero","febrero","marzo","abril","Mayo","junio",;
				"julio","agosto","septiembre","octubre","noviembre","recuerdo","Prueba","comida","Método","Naciones Unidas. Mesurado","Especificado","Encontró",;
				"Cuenta total","Conde de moho y levadura","Recuento total de coliformes","Staphylococcus Aureus Count","ShelfLife 180 días","LABFIS","Viscosidad",;
				"Aprobado Sin restricciones","Contaminantes","Análisis externo","AFLATOXIN","ARSÉNICO","DIRIGIR","CADMIO","HAGO SOLAMENTE CANS LCO","ESTAÑO","Informe",;
				"Fecha. Informe","Qty. Rej","Sólo. Informe","Aprobado sin restricciones","Métodos","RESULTADOS","unidad","Max","ARTÍCULOS","Analista de laboratorio",;
				"Analista Microbiología","Coordinador de CQ y GQ","DENSIDAD","GRASA","SOLIDOS TOTALES","ACIDEZ","pH","VISCOSIDAD","BRIX","HUMEDAD","CRISTALIZACIÓN",;
				"VISCOSIDAD","día","SENSORIAL","LABFIS","ASPECTO","NOTA","COLOR","OzzLOR","TEXTURA","PH 4 DÍAS","EXP (WAL, TO, CH, VAN, OM","MERCADO EXTERNO",;
				"VIDA ÚTIL 210 DIAS","VIDA ÚTIL 240 DÍAS","CONTRA PRUEBA DE 150 DÍAS","VIDA ÚTIL 60 DÍAS","PROCESO DE LANZAMIENTO","VIDA ÚTIL 150 DÍAS","PREPARANDO CRE HERCULES",;
				"INST BAG CARGIL","MICROBIOLGIA","PHYSICOCHEMICAL","VIDA ÚTIL 360 DÍAS","VIDA ÚTIL 510 DIAS","VIDA ÚTIL 540 DÍAS","ACCOMP. EMBALAJE","FISICA QUIMICA",;
				"CONTENEDOR LCO","ALMACENAMIENTO DE TANQUE","ESTABILIZADO","VIDA ÚTIL 120 DÍAS","PREPARANDO CRE ING / ESP","LIOTÉCNICA / BULK","VIDA ÚTIL 180 DÍAS",;
				"VIDA ÚTIL 390 DIAS","CONTRA PRUEBA","PASTEURIZADO","VIDA ÚTIL 30 DÍAS","VIDA ÚTIL 90 DÍAS","NACIONAL","ARCOR-GRANEL","ARCOR BIG BAG 5KG","MEZCLA DE CHOCOLATE",;
				"ACCOMP. EMBALAJE","LECHE ESTANDARIZADA","VIDA ÚTIL 270 DÍAS","VIDA ÚTIL 450 DÍAS","VIDA ÚTIL 480 DÍAS","MICROBILOGÍA","ALMACENAMIENTO DE LA LIBERACIÓN",;
				"LECHE UHT ACCOMP","PREPARANDO EL CREME MOCOCA","VIDA ÚTIL 420 DÍAS","MICROLOGÍA","MICROBIOLOGÍA","LECHE UHT PA FQ","JARABE DE BBL","BOLSA DE BOXEO",;
				"FÍSICA QUÍMICA 1DÍA","CREAM UHT PA FQ","ACOMPAÑAMIENTO DE SILO","FOTOS DE 4 DÍAS","SENSORIAL","EXP (LA CAMP, CAMPESTR","GUARNICIÓN","ESTANDARIZADO",;
				"INSTITUCIONAL (BOLSA)","EXPORT (EE. UU.)","FASES","CREMA UHT ACCOMP","VIDA ÚTIL 300 DÍAS","VIDA ÚTIL 330 DÍAS","LCO BOXEO","ACCOMP. CREMA CRU","G / M²",;
				"PORCENTAJE","NIVEL","MILIGRAMA / KILOGRAM","JUEGO","KILOGRAMO","EQUIPO","PULGADAS","YARDA","CENTIPOISE","NANOMETRO","UNIDAD DE FORMACIÓN DE COLMENAS DE CRECIMIENTO",;
				"HOJA","ROTACIÓN POR MINUTO","GRAUS BRIX","NÚMERO POR 100g","ACORN DORNIC","GRAMOS","GRADOS POR CENTIMETRO CUADRADO","GRAMOS POR METRO CUBICO",;
				"MICROGRAMAR / KILOGRAM","RODAR","CANGILÓN","CENTÍMETRO","LÍQUIDO TONIFICADO","MINUTOS","UNIVERSIDAD DE COLONIA","Molinero","GRAUS Z","POTENCIAL DE HIDROGENO",;
				"UNIDAD DE FORMACIÓN COLONIAL","MALLA","CONJUNTO","° DORNIC","NIVEL","GRAMAS PER METRO QUDRADO","DECÍMETRO","DOCENA","HOJAS","GROZA","HORA","LITRO",;
				"ESTAÑO","ºGL","PARTÍCULAS MAGNETICAS","UFC / 100cm²","ML","MICRO","BLOQUEAR","NITIDEZ POR TURBIDEZ","UNIDAD","Cero","UI-Max","POTENCIAL DE HIDROGENO",;
				"GRAUS GL","ºD","PUB","kg / m²","BOTELLA","PAQUETE","METRO CUADRADO","PAR","ÁCIDO LÁCTICO","CUADRADO FORZADO POR EL CENTÍMETRO CUADRADO","GRADOS CENTIGADOS",;
				"UNIDAD DE ENTRENAMIENTO","CUENTA DE CÉLULAS SOMÁTICAS","~ HAZEN","NEWTON POR METRO","MILIGRAMO","GRAMAS PER LITRO","CENTÍMETRO CUADRADO","MILAMPER",;
				"Fuego","CENTÍMETRO CÚBICO","CENTO","CAJERO","CÉSPED","LB","METRO CÚBICO","SUBTERRANEO","JAGUAR","SEGUNDOS","Volumen","GRAMOS POR ML","PIE","GALÓN",;
				"MILILITRO","PIEZA","CINZAS","Kgf / cm","MIRIAMETRO","MINUTO","PRUEBA","GRAMOS POR METRO","KILOGRAM FORCA PER CENTIMETER","BOLSO","NOTA DEL 1 AL 5",;
				"ESCALA DE HUMEDAD","GRAUS H","BANDEJA","MILÍMETRO","CENTIGRADOS","GRAMOS POR MILILITROS","FUERZAS DE KILOGRAM POR CENTIMETRO CÚBICO","PARTE PARA MILLONES",;
				"UNID.FOR.COLONIAS POR QUADRAD CENTIMETER","NÚMERO MÁS PROVABLE","ACTIVIDAD DE PROTEASAS","fregonas","Cps","TONELADA","GRAMOS CIENTÍFICOS","GRAVES POR CENTIMETRO CÚBICO",;
				"CUENTA TOTAL","CUENTA DE COLIFORMES TOTALES","BACILLUS CEREUS","VISCOSIDAD 1ºDIA","BRIX 1ºDIA","SENSORIAL","VISCOSIDAD 6 ° DÍA","GORDURA","TEMPERATURA","VISCOSIDAD","ASPECTO",;
				"COLOR","VOLUMEN (TANQUE)","CUENTA DE STAPHYLOCOCCUS AUREUS","ACIDEZ","Odor","SORO","PEROXIDASE","BRIX","CUENTA DE BACILLUS SPOROTHERMODURANS","PSICOTROFICOS",;
				"DENSIDAD","CUENTA DE COLIFORMES TERMOTOLERANTES","FOSFATASE","CONTAGEN DE MESÓFILOS AERÓBIOS VIBRALES","ODOR","EXTRATO SECO TOTAL","CRISCOPIA","SALMONELA","FORMALDEIDO (METODO LENTO)",;
				"FORMALDEIDO (METODO RAPIDO)","TEXTURA","SABOR","pH","ALCOOL","UNIDAD","CRISTALIZACION","pH 1ºDIA","SOLIDOS TOTALES","EXTRATO SECO DESENGORDURADO","CUENTA DE COLIFORMES TERMOTOLERANTE",;
				"SOLIDOS NO GORDUROSOS","PEROXIDO DE HIDROGENO","CUENTA DE MICROORGANISMOS PSICOTROFICO","ENCUADRADO BBL","ENVASE CRE","ENVASE TP","FABRICACIÓN LECHE PO","DESN / PASTEURIZ","ENVASE LCO","FABRICACIÓN MIX BBL","FABRICACIÓN BBL","FABRICACIÓN CRE","ENVASE 1 KG","RECEPCIÓN SORO LIQ","RECEPCIÓN DESN","ENVASE BAG",;
				"ENVASE BBL","FABRICACIÓN LCO","FABRICACIÓN MIX LCO","FABRICACIÓN MIX CRE","RESFRIAMIENTO LECHE","FABRICACIÓN SORO PO","ENCAJOT LECHE","ENVASE CREMA","FABRICACIÓN CALDA","ENVASE LECHE UHT","ENCAJES 1KG","ENCAJOTAMIENTO BAG",;
				"ENCENDIDO TP","ENCUADRO CREADO","FABRICACIÓN XAROPE","RECEPCIÓN CREMA","PREPARACION CREMA","RECIBIR PERMISO","ENCAJE LECHE","PADRONIZACIÓN LCO","RECEPCIÓN LECHE","RESFRIAMIENTO CREMA","ENCUADRADO LCO","PADRONIZACION LOTE",;
				"ENCAJOT CREME","ENVASE 1KG","FABRICACION LCO","Aflatoxina","Arsénico","Plomo","Cdmio","Estaño","Analisis Externo","ACEPTO CON DESVIOS SIMPLE","REJETIVO TOTALMENTE","ACEPTO CON DESVIO GRAVE","CON SELECCIÓN POR EL PRODUCTO","LIBERACIÓN URGENTE"}

Local aPalavIngles:= {"Total Count","Molds and Yeasts","Staphylococcus aureus","Total Coliforms","Salmonella spp","Thermotolerant Col.","Bacillus cereus",;
				"Ph","APPROVED WITHOUT RESTRICTIONS ***","Note","Minimum","Maximum","Product","Date of Production","Client","Shelf life","Order","Container","Lot","Issued Qty","Certificate of Analysis",;
				"Operation","Quality certificate","presence","absence","group","company","leaf","dt.ref","emission","January","February","March","April","May","June","July",;
				"August","September","October","November","I remember","Test","food","Method","Un. Measured","Specified","Found","Total Count","Mold and Yeast Count",;
				"Total Coliform Count","Staphylococcus Aureus Count","ShelfLife 180 Days","LABFIS","Viscosity","Approved No Restrictions","Contaminants","External Analysis",;
				"AFLATOXIN","ARSENIC","LEAD","CADMIUM","I MAKE ONLY CANS LCO","TIN","Report","Date. Report","Qty. Rej","Just. Report","Approved without Restrictions",;
				"Methods","RESULTS","unity","Max","ITEMS","Laboratory Analyst","Analyst Microbiology","CQ and GQ Coordinator","DENSITY","FAT","TOTAL SOLIDS","ACIDITY",;
				"pH","VISCOSITY","BRIX","MOISTURE","CRYSTALLIZATION","VISCOSITY","day","SENSORY","LABFIS","ASPECT","NOTE","COLOR","ODOR","TEXTURE","PH 4 DAYS","EXP (WAL, TO, CH, VAN, OM",;
				"EXTERNAL MARKET","SHELF LIFE 210 DAYS","SHELF LIFE 240 DAYS","AGAINST PROOF 150 DAY","SHELF LIFE 60 DAYS","RELEASE PROCESS","SHELF LIFE 150 DAYS",;
				"PREPARING CRE HERCULES","INST BAG CARGIL","MICROBIOLGY","PHYSICOCHEMICAL","SHELF LIFE 360 DAYS","SHELF LIFE 510 DAYS","SHELF LIFE 540 DAYS"," ACCOMP. PACKAGING",;
				"CHEMICAL PHYSICS","LCO CONTAINER","TANK STORAGE","STABILIZED","SHELF LIFE 120 DAYS","PREPARING CRE ING / ESP","LIOTÉCNICA / BULK","SHELF LIFE 180 DAYS",;
				"SHELF LIFE 390 DAYS","AGAINST PROOF","PASTEURIZED","SHELF LIFE 30 DAYS","SHELF LIFE 90 DAYS","NATIONAL","ARCOR-GRANEL","ARCOR BIG BAG 5KG","CHOCOLATE MIXTURE",;
				"ACCOMP. PACKAGING","STANDARDIZED MILK","SHELF LIFE 270 DAYS","SHELF LIFE 450 DAYS","SHELF LIFE 480 DAYS","MICROBILOGY","STOCKING LIBERATION","MILK UHT ACCOMP",;
				"PREPARING CREME MOCOCA","SHELF LIFE 420 DAYS","MICROLOGY","MICROBIOLOGY","MILK UHT PA FQ","BBL SYRUP","BOXING BAG","PHYSICS CHEMICAL 1DAY","CREAM UHT PA FQ",;
				"SILO ACCOMPANIMENT","4 DAY PHOTOS","SENSORY","EXP (LA CAMP, CAMPESTR","SIDE DISH","STANDARDIZED","INSTITUTIONAL (BAG)","EXPORT (USA)","PHASES","CREAM UHT ACCOMP",;
				"SHELF LIFE 300 DAYS","SHELF LIFE 330 DAYS","LCO BOXING","ACCOMP. CREAM CRU","G / M²","PERCENTAGE","LEVEL","MILIGRAMA / KILOGRAM","GAME","KILOGRAM","KIT",;
				"INCHES","YARD","CENTIPOISE","NANOMETRO","GROWTH COLONY FORMING UNIT","LEAF","ROTATION PER MINUTE","GRAUS BRIX","NUMBER PER 100g","ACORN DORNIC","GRAMS",;
				"GRADES PER SQUARE CENTIMETER","GRAMS BY CUBIC METRO","MICRO GRAMMAR / KILOGRAM","ROLL","BUCKET","CENTIMETER","TONNED LIQUID","MINUTES","UNIVERSITY OF COLOGNE",;
				"Miller","GRAUS Z","HYDROGEN POTENTIAL","COLONIAL FORMING UNIT","MESH","SET","° DORNIC","LEVEL","GRAMAS PER METRO QUDRADO","DECIMETER","DOZEN","SHEETS","GROZA",;
				"HOUR","LITER","TIN","ºGL","MAGNETIC PARTICLES","UFC / 100cm²","ML","MICRO","BLOCK","SHARPNESS BY TURBIDITY","UNITY","Zero","UI-Max","HYDROGEN POTENTIAL",;
				"GRAUS GL","ºD","PUB","kg / m²","BOTTLE","PACKAGE","SQUARE METER","PAIR","LACTIC ACID","QUADOGRAM FORCED BY SQUARE CENTIMETER","CENTIGRATED GRADES","TRAINING UNIT",;
				"COUNTING OF SOMATIC CELLS","~ HAZEN","NEWTON BY METRO","MILLIGRAM","GRAMAS PER LITRO","SQUARE CENTIMETER","MILAMPER","Fire","CUBIC CENTIMETER","CENTO",;
				"CASHIER","GRASS","LB","CUBIC METER","SUBWAY","JAGUAR","SECONDS","Volume","GRAMS BY ML","FOOT","GALLON","MILLILITER","PIECE","CINZAS","Kgf / cm","MIRIAMETRO",;
				"MINUTE","TEST","GRAMS PER METER","KILOGRAM FORCA PER CENTIMETER","BAG","NOTE FROM 1 TO 5","MOISTURE SCALE","GRAUS H","TRAY","MILLIMETER","CENTIGRADOS",;
				"GRAMS PER MILILITERS","KILOGRAM FORCES BY CUBIC CENTIMETER","PART FOR MILLION","UNID.FOR.COLONIAS BY QUADRAD CENTIMETER","MOST PROVABLE NUMBER",;
				"PROTEASE ACTIVITY","mops","Cps","TONNE","CENTIMETER GRAMS","GRAVES BY CUBIC CENTIMETER","TOTAL COUNT","COLLATERAL TOTAL COUNT","BACILLUS CEREUS","viscosity 1º day","BRIX 1º DAY","SENSORY","VISCOSITY 6TH DAY","FAT","TEMPERATURE","VISCOSITY","ASPECT","COLOR","VOLUME (TANK)",;
				"STAPHYLOCOCCUS AUREUS COUNT","ACIDITY","COUNTING OF BOLORES AND YEVES","SERUM","PEROXIDASE","BRIX","COUNTING OF BACILLUS SPOROTHERMODURANS","PSYCHOTHERAPISTS","DENSITY","COUNTING OF THERMOTOLERANT COLIFORMES",;
				"FOSFATASE","COUNTING OF VIABLE AERODE MESOPHILS","ODOR","TOTAL DRY EXTRACT","CRIOSCOPY","SALMONELA","FORMALDEIDO (SLOW METHOD)","FORMALDEIDO (QUICK METHOD)","TEXTURE","FLAVOR","pH","ALCOHOL","MOISTURE","CRYSTALLIZATION",;
				"pH 1ºDIA","TOTAL SOLIDS","DEGREASED DRY EXTRACT","COUNTING OF THERMOTRONATING COLIFORMES","NON-FATTY SOLIDS","HYDROGEN PEROXIDE","PSYCHOTROPIC MICROORGANISMS COUNT",;
				"BBL BOXING","CREW PACKAGING","TP PACK","MANUFACTURING MILK PO","DESN / PASTEURIZ","LCO CONTAINER","MIX BBL MANUFACTURING","BBL MANUFACTURING","CRE CREATION","PACKAGING 1 KG","SORO LIQ RECEIPT","RECEIPT OF DESN",;
				"CONTAINER BAG","BBL CONTAINER","LCO MANUFACTURE","MIX LCO MANUFACTURING","MIX CRE CREATION","COOLING MILK","MANUFACTURE SERUM PO","ENCAIXOT MILK","CREAM PACKAGING","MANUFACTURE CALDA","UHT MILK PACK","BOXING 1KG",;
				"BOXING BAG","TP BOXING","CREAM BOXING","MANUFACTURE SYRUP","CREME RECEPTION","CREAM PREPARATION","PERM RECEIPT","ENCAIX MILK","LCO STANDARDIZATION","MILK RECEPTION","COOLING CREME","LCO BOXING","STANDARD BATCH","CREAM ENCAIXOT",;
				"PACKAGING 1KG","LCO MANUFACTURING","Aflatoxin","Arsenic","Lead","Cadmium","Tin","External Analysis","I ACCEPT WITH SIMPLE DEVIATION","REJECTED TOTALLY","I ACCEPT SERIOUS DEVIATION","WITH SELECTION BY PRODUCT","URGENT RELEASE"}
					
	Local cBkpStrg 		:= CapitalAce(AllTrim(_cString))
	Local cBkpStr 		:= "/"+CapitalAce(AllTrim(_cString))
	Default _cString 	:= ""
	Default _cIdioma	:= ""
	
	
	/*if 	Upper(AllTrim(_cString)) $ "CONTAGEM DE BOLORES E LEVEDURAS"
	
			_cString := "Bolores e Leveduras"
			
	elseif Upper(AllTrim(_cString)) $ "CONTAGEM DE COLIFORMES TERMOTOLERANTES"
	
			_cString := "Col. Termotolerantes"
			
	elseif Upper(AllTrim(_cString)) $ "SALMONELA"
	
			_cString := "Salmonella spp"
			
	elseif Upper(AllTrim(_cString)) $ "CONTAGEM DE COLIFORMES TOTAIS"
	
			_cString := "Coliformes Totais"
			
	elseif Upper(AllTrim(_cString)) $ "CONTAGEM DE STAPHYLOCOCCUS AUREUS"
	
			_cString := "Estafilococos aureus"
			
	endif*/


	if !_cIdioma$"Portugês"


		if _cIdioma$"Inglês"

			_cString := funTraducao(_cString,aPalavPort,aPalavIngles)
			if !Upper(AllTrim(NoAcento(cBkpStrg)))$"ANALISE EXTERNA"
				_cString += cBkpStr
			endif

		elseif _cIdioma$"Espanhol"

			_cString := funTraducao(_cString,aPalavPort,aPalavEsp)
			if !Upper(AllTrim(NoAcento(cBkpStrg)))$"ANALISE EXTERNA"
				_cString += cBkpStr
			endif

		endif
		
	else
	
		_cString := AllTrim(CapitalAce(_cString)) 

	endif
	

Return(iif(len(_cString)>42,SubStr(_cString,1,42),_cString))

//***********************************************************
//Função que traduz para do portugês para o Inglês||Espanhol.
//***********************************************************

Static Function funTraducao(_cString,_aTraduzDe,_aTraduzPara)

	Default _aTraduzDe	 := {}
	Default _aTraduzPara := {}
	Default _cString 	 := ""

	for i := 1 to len(_aTraduzDe)

		if Upper(AllTrim(_cString))$Upper(AllTrim(_aTraduzDe[i]))

			_cString := CapitalAce(AllTrim(_aTraduzPara[i]))
			Exit
			 
		endif

	next i

return(CapitalAce(AllTrim(_cString)))